[connections.mysql]
type = "sql"
dialect = "mysql"  # 데이터베이스의 dialect 추가
port = 3306
host = "localhost"
database = "finals_20215217_CASE02"
username = "final_exam_20215217"  # '@localhost' 포함 가능
password = "case02"

